; Upload limits
upload_max_filesize = 2G
post_max_size = 3G
mbstring.http_input = pass
mbstring.http_output = pass
mbstring.internal_encoding = pass
memory_limit = 2G
allow_url_include = on;

; Execution
max_execution_time = 6000
max_input_time = 3000

; Laravel performance
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Opcache (Laravel recommended)
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0

; Security
expose_php=Off

; Error logging
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2

; Timezone (important for Laravel queues & logs)
date.timezone=Asia/Manila

cgi.fix_pathinfo=0
